# Generated by Django 4.2.7 on 2023-12-23 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(default=datetime.datetime(2023, 12, 23, 20, 43, 43, 371019, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
