# Generated by Django 4.2.7 on 2023-12-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0002_meseros_procedencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meseros',
            name='procedencia',
        ),
        migrations.AddField(
            model_name='meseros',
            name='dni',
            field=models.IntegerField(default='00000000'),
        ),
    ]
